name: Build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: vcpkg install
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: c8696863d371ab7f46e213d8f5ca923c4aef2a00
          runVcpkgInstall: true
          runVcpkgFormatString: '[`install`, `--recurse`, `--x-install-root`, `$[env.VCPKG_INSTALLED_DIR]`, `--triplet`, `$[env.VCPKG_DEFAULT_TRIPLET]`]'
          vcpkgJsonGlob: '**/vcpkg.json'
        env:
          VCPKG_DEFAULT_TRIPLET: x64-windows

      - run: Compress-Archive ./vcpkg/packages vcpkg_packages.zip

      - name: Upload vcpkg packages
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg
          path: vcpkg_packages.zip