name: Build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: vcpkg install
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: c8696863d371ab7f46e213d8f5ca923c4aef2a00
          runVcpkgInstall: true
          vcpkgJsonGlob: '**/vcpkg.json'
        env:
          VCPKG_DEFAULT_TRIPLET: x64-windows

      - run: Compress-Archive ./vcpkg vcpkg.zip

      - name: Upload vcpkg
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg
          path: vcpkg.zip